name: "Shirren's Action in Action"
description: "Greets someone and returns 23 always."
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  answer:
    description:  "The answer to everything is always 23"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}